function SA.CAFInit()
	SA.RD = CAF.GetAddon("Resource Distribution")
	SA.SB = CAF.GetAddon("Spacebuild")
	SA.LS = CAF.GetAddon("Life Support")

	timer.Simple(0, function()
		SA.RD.AddProperResourceName("valuable minerals", "Valuable Minerals")
		SA.RD.AddProperResourceName("dark matter", "Dark Matter")
		SA.RD.AddProperResourceName("terracrystal", "Terracrystal")
		SA.RD.AddProperResourceName("permafrost", "Permafrost")
		SA.RD.AddProperResourceName("ore", "Ore")
		SA.RD.AddProperResourceName("tiberium", "Tiberium")
		SA.RD.AddProperResourceName("metals", "Metals")
	end)
end
