name: Lint

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - name: Set up NodeJS LTS
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        check-latest: true
    - name: npm for Lua lint
      run: |
        set +ex
        export PATH=$PATH:/tmp/bin
        mkdir -p /tmp/bin
        pushd /tmp/bin
        wget -q https://github.com/FPtje/GLuaFixer/releases/download/1.28.0/glualint-1.28.0-x86_64-linux.zip -O glualint.zip
        unzip glualint.zip
        chmod +x glualint
        popd
        echo "Running linter..."
        node gluaLintEx.js
      env:
        CI: true
